apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-container
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-crypto-global
  volumeName: ''